In [2]:
import os
from math import log
from IPython.display import display

import pandas as pd
from utils.utils import load_from_dir, save_data

In [3]:
def select_fc(df: pd.DataFrame, fc_column: str) -> pd.DataFrame:
    selected_df = df[df[fc_column].abs() > 2]
    display(selected_df.shape)
    return selected_df

def select_pval(df: pd.DataFrame, pval_column: str, threshold: float) -> pd.DataFrame:
    selected_df = df[df[pval_column] <= threshold]
    display(selected_df.shape)
    return selected_df

In [4]:
data = load_from_dir("../data/raw/", suffix="xlsx")

0it [00:00, ?it/s]

,Length,DS2bw/DS2.fc,DS2bw/DS2.fc.sd,DS2bw/DS2.volume,DS2bw/DS2.stat_results,DS2bw/DS2.raw.pval,DS2bw/DS2.bh.pval,DS2.mean,DS2bw.mean,DS2.sd,...,N_DS2_1,N_DS2_2,N_DS2bw1,N_DS2bw2,N_DS2bw3,DS2_1_FPKM,DS2_2_FPKM,DS2bw1_FPKM,DS2bw2_FPKM,DS2bw3_FPKM
count,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,...,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000,85616.000000
mean,1391.807337,-0.003051,0.250764,1.417242,-0.059158,0.457797,0.879777,1.425279,1.425280,0.150949,...,1.425325,1.425234,1.425173,1.425308,1.425359,10.472475,10.470819,10.831769,10.394924,10.711416
std,1042.029805,1.171934,0.207792,1.472297,2.360569,0.288305,0.062760,1.478504,1.475193,0.171627,...,1.487274,1.487348,1.487391,1.487260,1.487263,209.916355,208.549221,276.415706,245.087943,220.741219
min,201.000000,-10.070027,0.000000,0.014355,-56.543968,0.000005,0.409446,0.014355,0.014355,0.000000,...,0.014355,0.014355,0.014355,0.014355,0.014355,0.010000,0.010000,0.010000,0.010000,0.010000
25%,646.000000,-1.089103,0.120299,0.384582,-0.991569,0.204663,0.818285,0.384723,0.387790,0.043530,...,0.375907,0.375907,0.369204,0.378188,0.378188,0.340000,0.320000,0.260000,0.270000,0.300000
50%,1110.000000,-1.000619,0.195840,0.884154,-0.007977,0.432650,0.865242,0.895127,0.894768,0.099731,...,0.895420,0.895420,0.893913,0.895420,0.895420,0.980000,0.920000,0.760000,0.780000,0.870000
75%,1841.000000,1.085325,0.313702,1.951649,0.989308,0.700761,0.934161,1.974099,1.966817,0.195693,...,1.985259,1.985259,1.985259,1.985259,1.985259,3.290000,3.110000,2.660000,2.760000,3.010000
max,16024.000000,21.483112,3.433980,15.434032,91.940503,1.000000,1.000000,15.434032,15.434032,2.583887,...,15.434032,15.434032,15.434032,15.434032,15.434032,40426.720000,38758.840000,56508.500000,49773.320000,38577.520000

(85616, 23)

1it [00:30, 30.72s/it]

,Length,M12bw/M12wn.fc,M12bw/M12wn.fc.sd,M12bw/M12wn.volume,M12bw/M12wn.stat_results,M12bw/M12wn.raw.pval,M12bw/M12wn.bh.pval,M12wn.mean,M12bw.mean,M12wn.sd,...,N_M12bw1,N_M12bw2,N_M12bw3,N_M12wn2,N_M12wn3,M12bw1_FPKM,M12bw2_FPKM,M12bw3_FPKM,M12wn2_FPKM,M12wn3_FPKM
count,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,...,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.000000,79785.00000
mean,1420.751244,0.031077,0.236554,1.393339,0.050877,0.423972,0.757375,1.403899,1.403920,0.154710,...,1.403863,1.403984,1.403912,1.403979,1.403819,10.946854,11.183794,11.258611,10.981461,10.29696
std,1056.926034,1.239931,0.196251,1.482886,2.953922,0.294448,0.158095,1.491574,1.491734,0.174682,...,1.500676,1.500618,1.500661,1.500615,1.500731,256.441998,293.048194,292.249560,216.329864,163.17098
min,201.000000,-43.186443,0.000000,0.014355,-71.402145,0.000013,0.402095,0.014355,0.014355,0.000000,...,0.014355,0.014355,0.014355,0.014355,0.014355,0.010000,0.010000,0.010000,0.010000,0.01000
25%,661.000000,-1.088807,0.112134,0.362237,-1.063698,0.161393,0.645528,0.363114,0.365186,0.044720,...,0.355758,0.355758,0.355758,0.344436,0.355758,0.270000,0.250000,0.250000,0.300000,0.32000
50%,1142.000000,1.005361,0.184811,0.840774,0.071063,0.386356,0.772695,0.855767,0.851777,0.103424,...,0.857689,0.857689,0.857689,0.857689,0.857689,0.790000,0.740000,0.720000,0.890000,0.93000
75%,1875.000000,1.102294,0.298880,1.914786,1.198712,0.668166,0.890884,1.937905,1.932897,0.203778,...,1.950755,1.951897,1.949254,1.951562,1.949254,2.780000,2.620000,2.570000,3.110000,3.30000
max,16024.000000,24.306277,3.556487,15.354086,77.944698,1.000000,1.000000,15.354086,15.354086,3.344173,...,15.354086,15.354086,15.354086,15.354086,15.354086,46859.440000,54050.450000,54513.150000,35516.360000,26279.79000

(79785, 23)

2it [00:58, 29.89s/it]

,Length,RXLbw/RXL.fc,RXLbw/RXL.fc.sd,RXLbw/RXL.volume,RXLbw/RXL.stat_results,RXLbw/RXL.raw.pval,RXLbw/RXL.bh.pval,RXL.mean,RXLbw.mean,RXL.sd,RXLbw.sd,N_RXL1,N_RXL2,N_RXLbw1,N_RXLbw2,RXL1_FPKM,RXL2_FPKM,RXLbw1_FPKM,RXLbw2_FPKM
count,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000,81630.000000
mean,1413.880644,-0.020551,0.234506,1.385521,-0.094786,0.472020,0.916355,1.395490,1.395422,0.141011,0.156115,1.395541,1.395439,1.395447,1.395398,10.754922,10.587711,11.057085,11.285843
std,1049.686693,1.205907,0.195783,1.473043,6.308946,0.277765,0.033777,1.479774,1.478410,0.150223,0.162791,1.486874,1.486984,1.486971,1.487004,223.570918,179.198736,265.438067,309.376811
min,201.000000,-32.376936,0.000000,0.014355,-703.920006,0.000030,0.893147,0.014355,0.014355,0.000000,0.000000,0.014355,0.014355,0.014355,0.014355,0.010000,0.010000,0.010000,0.010000
25%,661.000000,-1.099665,0.104029,0.366644,-1.123780,0.235378,0.893147,0.365431,0.368854,0.041617,0.047493,0.355753,0.355753,0.355753,0.358582,0.270000,0.330000,0.270000,0.250000
50%,1136.000000,-1.003118,0.184007,0.836406,-0.039202,0.448510,0.896715,0.849395,0.849982,0.096690,0.110409,0.854644,0.854644,0.856498,0.856498,0.800000,0.940000,0.770000,0.730000
75%,1866.000000,1.092638,0.304372,1.904775,0.984289,0.701241,0.934964,1.928527,1.921581,0.188697,0.211015,1.938516,1.938516,1.936555,1.938516,2.850000,3.270000,2.720000,2.530000
max,16024.000000,36.848322,4.694437,15.393799,360.482557,1.000000,1.000000,15.393799,15.393799,3.390874,3.403185,15.393799,15.393799,15.393799,15.393799,40198.410000,25834.190000,51852.990000,63791.140000

(81630, 21)

3it [01:25, 28.38s/it]

In [6]:
rxl = data.get("RXL")[["GO", "RXLbw/RXL.fc", "RXLbw/RXL.raw.pval", "N_RXL1", "N_RXL2", "N_RXLbw1", "N_RXLbw2"]]
display(rxl.head())

ds2 = data.get("DS2")[["GO", "DS2bw/DS2.fc", "DS2bw/DS2.raw.pval", "N_DS2_1", "N_DS2_2", "N_DS2bw1", "N_DS2bw2", "N_DS2bw3"]]
display(ds2.head())


m12 = data.get("M12")[["GO", "M12bw/M12wn.fc", "M12bw/M12wn.raw.pval", "N_M12bw1", "N_M12bw2", "N_M12bw3", "N_M12wn2", "N_M12wn3"]]
display(m12.head())

,GO,RXLbw/RXL.fc,RXLbw/RXL.raw.pval,N_RXL1,N_RXL2,N_RXLbw1,N_RXLbw2
Contig,,,,,,,
c58_g1_i1,.,-1.440769,0.168326,0.948945,0.856498,0.537828,0.213939
c75_g1_i1,.,-1.121267,0.636671,0.418976,0.933905,0.537828,0.484794
c100_g1_i1,TAIR|locus:2134123 - symbol:AT4G32870 AT4G3287...,1.046020,0.725316,0.060035,0.238607,0.084032,0.344431
c105_g1_i1,.,1.143527,0.158562,0.204594,0.111000,0.283600,0.418976
c116_g1_i1,.,-1.088905,0.159125,0.341689,0.405536,0.247741,0.253729

,GO,DS2bw/DS2.fc,DS2bw/DS2.raw.pval,N_DS2_1,N_DS2_2,N_DS2bw1,N_DS2bw2,N_DS2bw3
Contig,,,,,,,,
c58_g1_i1,.,-1.253778,0.231288,1.302723,1.261141,0.582276,1.060547,1.224128
c100_g1_i1,TAIR|locus:2134123 - symbol:AT4G32870 AT4G3287...,1.077082,0.264728,0.223905,0.188923,0.214018,0.449423,0.277186
c104_g1_i1,.,1.018095,0.760636,0.075859,0.165995,0.094876,0.272395,0.073124
c116_g1_i1,.,-1.138862,0.413884,0.572603,0.268833,0.108322,0.204067,0.386985
c123_g1_i1,.,1.111505,0.325058,0.303086,0.344489,0.410987,0.705561,0.312359

,GO,M12bw/M12wn.fc,M12bw/M12wn.raw.pval,N_M12bw1,N_M12bw2,N_M12bw3,N_M12wn2,N_M12wn3
Contig,,,,,,,,
c58_g1_i1,.,-1.276248,0.292010,1.228047,0.519241,0.492947,0.970574,1.226733
c76_g1_i1,.,-1.007992,0.981078,1.328680,0.742087,0.882869,1.368250,0.623809
c89_g1_i2,.,-1.101818,0.610101,0.081304,0.236165,0.445209,0.591761,0.196463
c89_g1_i1,.,-1.070309,0.733172,0.153078,0.415281,0.827326,0.735182,0.391328
c100_g1_i1,TAIR|locus:2134123 - symbol:AT4G32870 AT4G3287...,1.123931,0.209982,0.455634,0.402289,0.153078,0.183816,0.153078

In [7]:
save_data([rxl, ds2, m12], names=["RXL.csv", "DS2.csv", "M12.csv"], path="../data/interim")

In [8]:
# Select data

In [9]:
# RXL
rxl_selected_fc = select_fc(rxl, "RXLbw/RXL.fc")

rxl_selected_fc_05 = select_pval(rxl_selected_fc, "RXLbw/RXL.raw.pval", threshold=0.05)
rxl_selected_fc_005 = select_pval(rxl_selected_fc, "RXLbw/RXL.raw.pval", threshold=0.005)
rxl_selected_fc_001 = select_pval(rxl_selected_fc, "RXLbw/RXL.raw.pval", threshold=0.001)

save_data([rxl_selected_fc_05, rxl_selected_fc_005, rxl_selected_fc_001], names=["RXL_05.csv", "RXL_005.csv", "RXL_001.csv"], path="../data/prepared/")

(1000, 7)

(159, 7)

(14, 7)

(7, 7)

In [10]:
# DS2
ds2_selected_fc = select_fc(ds2, "DS2bw/DS2.fc")

ds2_selected_fc_05 = select_pval(ds2_selected_fc, "DS2bw/DS2.raw.pval", threshold=0.05)
ds2_selected_fc_005 = select_pval(ds2_selected_fc, "DS2bw/DS2.raw.pval", threshold=0.005)
ds2_selected_fc_001 = select_pval(ds2_selected_fc, "DS2bw/DS2.raw.pval", threshold=0.001)

save_data([ds2_selected_fc_05, ds2_selected_fc_005, ds2_selected_fc_001], names=["DS2_05.csv", "DS2_005.csv", "DS2_001.csv"], path="../data/prepared/")

(681, 8)

(175, 8)

(17, 8)

(2, 8)

In [11]:
# M12
m12_selected_fc = select_fc(m12, "M12bw/M12wn.fc")

m12_selected_fc_05 = select_pval(m12_selected_fc, "M12bw/M12wn.raw.pval", threshold=0.05)
m12_selected_fc_005 = select_pval(m12_selected_fc, "M12bw/M12wn.raw.pval", threshold=0.005)
m12_selected_fc_001 = select_pval(m12_selected_fc, "M12bw/M12wn.raw.pval", threshold=0.001)

save_data([m12_selected_fc_05, m12_selected_fc_005, m12_selected_fc_001], names=["M12_05.csv", "M12_005.csv", "M12_001.csv"], path="../data/prepared/")

(1456, 8)

(736, 8)

(163, 8)

(45, 8)